// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVqP_jL5l1NzyGt5cSkCLADg-6NxjWh8',
    appId: '1:766653213572:web:1065f3f34f301e29758bd1',
    messagingSenderId: '766653213572',
    projectId: 'atelier4-a-zakari',
    authDomain: 'atelier4-a-zakari.firebaseapp.com',
    storageBucket: 'atelier4-a-zakari.appspot.com',
    measurementId: 'G-MRVQVGBML8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhLPnl79XXuhPFPn8FExEiw6KECXt-Sc',
    appId: '1:766653213572:android:999151eb77ac60cf758bd1',
    messagingSenderId: '766653213572',
    projectId: 'atelier4-a-zakari',
    storageBucket: 'atelier4-a-zakari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gIZmbU1DYPIKABSV-vtkv3JTIj72q78',
    appId: '1:766653213572:ios:730df164b4bd6d6d758bd1',
    messagingSenderId: '766653213572',
    projectId: 'atelier4-a-zakari',
    storageBucket: 'atelier4-a-zakari.appspot.com',
    iosBundleId: 'com.example.atelier4AZakariIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1gIZmbU1DYPIKABSV-vtkv3JTIj72q78',
    appId: '1:766653213572:ios:6e5a24df169f8f15758bd1',
    messagingSenderId: '766653213572',
    projectId: 'atelier4-a-zakari',
    storageBucket: 'atelier4-a-zakari.appspot.com',
    iosBundleId: 'com.example.atelier4AZakariIir5g2.RunnerTests',
  );
}
